const seedUsers = [
  {
    name: 'GenZ Administrator',
    email: 'admin@eshop.com',
    phone: '9876543210',
    password: 'admin123',
    role: 'admin',
    address: {
      street: 'Penthouse 42, Cyber Hub, Silicon Avenue',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560100',
    },
  },
  {
    name: 'Aryan Kapoor',
    email: 'user@eshop.com',
    phone: '9123456780',
    password: 'user123',
    role: 'user',
    address: {
      street: 'Apt 14B, Skyline Residency, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
    },
  },
  {
    name: 'Ananya Sen',
    email: 'ananya@eshop.com',
    phone: '9988776655',
    password: 'user123',
    role: 'user',
    address: {
      street: '72 Green Valley, Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
    },
  },
];

const seedProducts = [
  {
    name: 'Apple AirPods Max Wireless Over-Ear Headphones (Silver)',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    category: 'Trending Tech',
    price: 59900,
    originalPrice: 64900,
    description: 'The ultimate aesthetic listening experience. High-fidelity audio, Active Noise Cancellation with Transparency mode, personalized spatial audio with dynamic head tracking, and breathable knit mesh canopy.',
    stock: 20,
    rating: 4.9,
    numReviews: 240,
    isFeatured: true,
  },
  {
    name: 'Oversized Heavyweight Anime Graphic Streetwear Hoodie ("Neo Tokyo")',
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    category: 'GenZ Streetwear',
    price: 2499,
    originalPrice: 3499,
    description: 'Viral drop-shoulder boxy fit crafted from 450 GSM ultra-heavy French terry cotton. Features cyber-aesthetic Japanese kanji puff prints with double-layered hood.',
    stock: 50,
    rating: 4.8,
    numReviews: 318,
    isFeatured: true,
  },
  {
    name: 'Y2K Vintage Washed Multi-Pocket Baggy Cargo Pants',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
    category: 'GenZ Streetwear',
    price: 2199,
    originalPrice: 2999,
    description: 'Retro washed relaxed parachute fit with 8 tactical 3D utility cargo pockets, adjustable drawstrings at hem, and high-density cotton ripstop weave.',
    stock: 35,
    rating: 4.7,
    numReviews: 184,
    isFeatured: true,
  },
  {
    name: 'Retro Polaroid Now+ I-Type Instant Bluetooth Camera',
    image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&auto=format&fit=crop&q=80',
    category: 'Aesthetic Gadgets',
    price: 14990,
    originalPrice: 16990,
    description: 'Connect via Bluetooth to the Polaroid app to unlock light painting, double exposure, manual mode, and 5 creative lens filters included in the box.',
    stock: 18,
    rating: 4.9,
    numReviews: 142,
    isFeatured: true,
  },
  {
    name: 'Stanley Quencher H2.0 FlowState Insulated Tumbler (40oz)',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
    category: 'Viral Lifestyle',
    price: 3499,
    originalPrice: 4499,
    description: 'The viral hydration icon. Double-wall vacuum insulation keeps iced drinks frosty for up to 48 hours. Features the advanced 3-position FlowState rotating lid and ergonomic handle.',
    stock: 40,
    rating: 4.9,
    numReviews: 520,
    isFeatured: true,
  },
  {
    name: 'New Balance 550 Retro Low-Top Vintage White/Green Sneakers',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    category: 'Kicks & Footwear',
    price: 10999,
    originalPrice: 12999,
    description: 'Tribute to 90s pro basketball ballers. Streamlined retro leather silhouette with contrast pine green accents, perforated leather vamp, and durable non-marking rubber outsole.',
    stock: 25,
    rating: 4.8,
    numReviews: 295,
    isFeatured: true,
  },
  {
    name: 'Sunset Projection 16-Color RGB Ambient Golden Hour Lamp',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
    category: 'Room Aesthetic',
    price: 1299,
    originalPrice: 1999,
    description: 'Create viral Golden Hour aesthetic lighting anytime. 360-degree rotatable aluminum head with high-transmittance crystal lens and wireless remote control.',
    stock: 60,
    rating: 4.6,
    numReviews: 410,
    isFeatured: false,
  },
  {
    name: 'Fujifilm Instax Mini 12 Instant Camera (Lilac Purple)',
    image: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80',
    category: 'Aesthetic Gadgets',
    price: 6999,
    originalPrice: 8499,
    description: 'Super bubbly design with close-up mode and selfie mirror. Automatic exposure and flash control so you can point, shoot, and print memories in credit-card format.',
    stock: 22,
    rating: 4.8,
    numReviews: 180,
    isFeatured: false,
  },
  {
    name: 'Keychron K2 Wireless Hot-Swappable RGB Mechanical Keyboard',
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80',
    category: 'Trending Tech',
    price: 8499,
    originalPrice: 9999,
    description: '75% compact layout with pre-lubed Gateron G Pro mechanical switches. Connects via Bluetooth 5.1 or USB-C with up to 3 devices across Mac and Windows.',
    stock: 28,
    rating: 4.9,
    numReviews: 215,
    isFeatured: true,
  },
  {
    name: 'Crocs Classic Clogs with 10pc Y2K Custom Jibbitz Charms Set',
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80',
    category: 'Kicks & Footwear',
    price: 2995,
    originalPrice: 3995,
    description: 'Lightweight, water-friendly Croslite foam clogs bundled with an exclusive 10-piece viral Y2K anime and pixel-art Jibbitz charm bundle.',
    stock: 30,
    rating: 4.7,
    numReviews: 178,
    isFeatured: false,
  },
  {
    name: 'Sony PlayStation 5 Slim Digital Edition (1TB NVMe)',
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
    category: 'Trending Tech',
    price: 44990,
    originalPrice: 49990,
    description: 'Play Has No Limits. Ultra-compact slim design, lightning-fast 1TB high-speed solid-state drive, 4K ray tracing visuals, and immersive 3D audio.',
    stock: 14,
    rating: 4.9,
    numReviews: 380,
    isFeatured: true,
  },
  {
    name: 'Vintage Bluetooth Suitcase Vinyl Record Player Turntable',
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop&q=80',
    category: 'Room Aesthetic',
    price: 5999,
    originalPrice: 7999,
    description: 'Classic suitcase design covered in retro faux leather with brass corners. 3-speed belt-driven turntable plays 33 1/3, 45, and 78 RPM records with wireless streaming.',
    stock: 16,
    rating: 4.7,
    numReviews: 95,
    isFeatured: false,
  },
  {
    name: 'COSRX Advanced Snail 96 Mucin Power Essence + Rice Mask Glow Kit',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&auto=format&fit=crop&q=80',
    category: 'Viral Lifestyle',
    price: 1450,
    originalPrice: 1950,
    description: 'The TikTok viral Korean glass-skin holy grail. 96.3% filtered snail secretion filtrate delivers deep hydration, repairs skin barrier, and imparts a healthy glass glow.',
    stock: 45,
    rating: 4.9,
    numReviews: 460,
    isFeatured: false,
  },
  {
    name: 'Retro Matrix Cyberpunk Wrap-Around Y2K Sunglasses',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
    category: 'GenZ Streetwear',
    price: 999,
    originalPrice: 1499,
    description: 'Futuristic shield wrap silhouette with mirrored UV400 lenses. Ultra-lightweight polycarbonate frame designed for raves, music festivals, and streetwear fits.',
    stock: 55,
    rating: 4.6,
    numReviews: 88,
    isFeatured: false,
  },
  {
    name: 'Aesthetic LED Cloud Ambient Ceiling Light with Lightning Mode',
    image: 'https://images.unsplash.com/photo-1519750157634-b6d493a0f77c?w=800&auto=format&fit=crop&q=80',
    category: 'Room Aesthetic',
    price: 3999,
    originalPrice: 5499,
    description: 'Transform your room into a dreamy sky. DIY 3D cloud lamp with music sync, RGB dynamic color changing, and realistic soft thunderstorm lightning effects.',
    stock: 20,
    rating: 4.8,
    numReviews: 125,
    isFeatured: false,
  },
  {
    name: 'Minimalist Water-Resistant Canvas Duffle & Gym Weekender',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
    category: 'Viral Lifestyle',
    price: 1899,
    originalPrice: 2699,
    description: 'Clean aesthetic weekender duffle bag with separate ventilated shoe compartment, dry/wet separation pocket, and luggage trolley strap for travel.',
    stock: 35,
    rating: 4.7,
    numReviews: 76,
    isFeatured: false,
  },
];

module.exports = { seedUsers, seedProducts };
